# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "0137487028f64c8ab9d9b13c1374d955"
name = "Variants Custom Fields"
application_url = "https://example.com"
embedded = true

[webhooks]
api_version = "2026-04"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [ "https://example.com/api/auth" ]

[build]
automatically_update_urls_on_dev = true
